name: HACS and Hassfest

on:
  pull_request:
    paths:
      - "custom_components/**"
      - "hacs.json"
      - ".github/workflows/hacs.yml"
  push:
    branches: [main]
    paths:
      - "custom_components/**"
      - "hacs.json"
      - ".github/workflows/hacs.yml"

permissions:
  contents: read

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: hacs/action@main
        with:
          category: integration

  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: home-assistant/actions/hassfest@master

  disposable-ha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install and upgrade package in disposable Home Assistant
        run: tests/test_hacs_ha_container.sh
